/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edgecompapp;
import javax.swing.JLabel;
import javax.swing.JSlider;
import java.awt.Color;


/**
 *
 * @author Biddrup Kumar Mallic
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        
            /// Start threads for each sensor
        new Thread(new SensorTask(sliderTemp, labelTempAlarm, labelTempActuator, 15, 25, 20, "Temperature")).start();
        new Thread(new SensorTask(sliderHumidity, labelHumidityAlarm, labelHumidityActuator, 60, 80, 70, "Humidity")).start();
        new Thread(new SensorTask(sliderMoisture, labelMoistureAlarm, labelMoistureActuator, 20, 30, 25, "Moisture")).start();
        new Thread(new SensorTask(sliderLight, labelLightAlarm, labelLightActuator, 20000, 40000, 30000, "Light")).start();


    }
    
    
    class SensorTask implements Runnable {
        private final JSlider slider;
        private final JLabel alarmLabel;
        private final JLabel actuatorLabel;
        private final int minIdeal, maxIdeal, perfectValue;
        private final String type;

        public SensorTask(JSlider slider, JLabel alarmLabel, JLabel actuatorLabel, int minIdeal, int maxIdeal, int perfectValue, String type) {
            this.slider = slider;
            this.alarmLabel = alarmLabel;
            this.actuatorLabel = actuatorLabel;
            this.minIdeal = minIdeal;
            this.maxIdeal = maxIdeal;
            this.perfectValue = perfectValue;
            this.type = type;
        }

        @Override
        public void run() {
            while (true) {
                try {
                    int value = slider.getValue();

                    if (value >= minIdeal && value <= maxIdeal) {
                        alarmLabel.setText("Normal");
                        alarmLabel.setBackground(Color.GREEN);
                        alarmLabel.setOpaque(true);

                        if (value == perfectValue) {
                            actuatorLabel.setText(type + " Control Off");
                        }
                    } else {
                        // Alarm logic
                        if (value < minIdeal) {
                            alarmLabel.setText(type + " too Low!");
                            actuatorLabel.setText(getActuatorLabel("low"));
                        } else {
                            alarmLabel.setText(type + " too High!");
                            actuatorLabel.setText(getActuatorLabel("high"));
                        }

                        alarmLabel.setBackground(Color.RED);
                        alarmLabel.setOpaque(true);

                        // Adjust the slider toward the perfect value (1 unit per 3 seconds)
                        new Thread(() -> {
                            try {
                                while (slider.getValue() != perfectValue) {
                                    int current = slider.getValue();
                                    if (current < perfectValue) {
                                        slider.setValue(current + 1);
                                    } else {
                                        slider.setValue(current - 1);
                                    }
                                    Thread.sleep(3000); // wait 3 seconds
                                }
                            } catch (InterruptedException e) {
                                e.printStackTrace();
                            }
                        }).start();
                    }

                    Thread.sleep(500); // main sensor check every 0.5 sec
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            }
        }

        private String getActuatorLabel(String direction) {
            switch (type) {
                case "Temperature":
                    return direction.equals("low") ? "Heating On" : "Cooling On";
                case "Humidity":
                    return direction.equals("low") ? "Humidifier On" : "Ventilation On";
                case "Moisture":
                    return direction.equals("low") ? "Irrigation On" : "Aeration On";
                case "Light":
                    return direction.equals("low") ? "Brightening On" : "Dimming On";
                default:
                    return "Control On";
            }
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        sliderTemp = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sliderHumidity = new javax.swing.JSlider();
        sliderMoisture = new javax.swing.JSlider();
        sliderLight = new javax.swing.JSlider();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        labelTempAlarm = new javax.swing.JLabel();
        labelTempActuator = new javax.swing.JLabel();
        labelHumidityAlarm = new javax.swing.JLabel();
        labelHumidityActuator = new javax.swing.JLabel();
        labelMoistureAlarm = new javax.swing.JLabel();
        labelLightAlarm = new javax.swing.JLabel();
        labelMoistureActuator = new javax.swing.JLabel();
        labelLightActuator = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("temerature"); // NOI18N

        jPanel1.setBackground(new java.awt.Color(64, 107, 173));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 50));

        jLabel13.setText("Dashboard");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel13)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jLabel1.setText("Temprature");

        sliderTemp.setMaximum(30);
        sliderTemp.setMinimum(10);
        sliderTemp.setValue(20);
        sliderTemp.setName("sliderTemp"); // NOI18N

        jLabel2.setText("Humidity");

        jLabel3.setText("Moisture");

        jLabel4.setText("Light");

        sliderHumidity.setMaximum(90);
        sliderHumidity.setMinimum(50);
        sliderHumidity.setValue(70);
        sliderHumidity.setName("sliderHumidity"); // NOI18N

        sliderMoisture.setMaximum(40);
        sliderMoisture.setMinimum(10);
        sliderMoisture.setValue(25);
        sliderMoisture.setName("sliderMoisture"); // NOI18N

        sliderLight.setMaximum(50000);
        sliderLight.setMinimum(10000);
        sliderLight.setValue(30000);
        sliderLight.setName("sliderLight"); // NOI18N

        jLabel7.setText("Alarm");

        jLabel8.setText("Actuator");

        jLabel9.setText("Alarm");

        jLabel10.setText("Actuator");

        jLabel11.setText("Alarm");

        jLabel12.setText("Actuator");

        jLabel5.setText("Alarm");

        jLabel6.setText("Actuator");

        labelTempAlarm.setText("Normal");

        labelTempActuator.setText("Temperature Control Off");

        labelHumidityAlarm.setText("Normal");

        labelHumidityActuator.setText("Humidity Control Off");

        labelMoistureAlarm.setText("Normal");

        labelLightAlarm.setText("Normal");

        labelMoistureActuator.setText("Moisture Control Off");

        labelLightActuator.setText("Light Control Off");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(sliderTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel3))
                                .addComponent(jLabel11))
                            .addComponent(jLabel7)
                            .addComponent(jLabel5))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(labelHumidityAlarm)
                                .addGap(140, 140, 140)
                                .addComponent(jLabel8)
                                .addGap(84, 84, 84)
                                .addComponent(labelHumidityActuator))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelLightAlarm)
                                        .addGap(156, 156, 156)
                                        .addComponent(jLabel12)
                                        .addGap(99, 99, 99)
                                        .addComponent(labelLightActuator))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(labelMoistureAlarm)
                                        .addGap(145, 145, 145)
                                        .addComponent(jLabel10)
                                        .addGap(93, 93, 93)
                                        .addComponent(labelMoistureActuator))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(sliderMoisture, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
                                        .addComponent(sliderHumidity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(sliderLight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(15, 15, 15)
                                            .addComponent(labelTempAlarm)
                                            .addGap(146, 146, 146)
                                            .addComponent(jLabel6)
                                            .addGap(67, 67, 67)
                                            .addComponent(labelTempActuator))))))))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sliderTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(labelTempAlarm)
                    .addComponent(labelTempActuator))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(sliderHumidity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(labelHumidityAlarm)
                    .addComponent(labelHumidityActuator))
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(sliderMoisture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(labelMoistureAlarm)
                    .addComponent(labelMoistureActuator))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(sliderLight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(labelLightAlarm)
                    .addComponent(labelLightActuator))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelHumidityActuator;
    private javax.swing.JLabel labelHumidityAlarm;
    private javax.swing.JLabel labelLightActuator;
    private javax.swing.JLabel labelLightAlarm;
    private javax.swing.JLabel labelMoistureActuator;
    private javax.swing.JLabel labelMoistureAlarm;
    private javax.swing.JLabel labelTempActuator;
    private javax.swing.JLabel labelTempAlarm;
    private javax.swing.JSlider sliderHumidity;
    private javax.swing.JSlider sliderLight;
    private javax.swing.JSlider sliderMoisture;
    private javax.swing.JSlider sliderTemp;
    // End of variables declaration//GEN-END:variables
}
